private-club/config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#home'

  resources :users

  get '/signup', to: 'users#new', as: 'signup'

  get    '/login',   to: 'sessions#new', as: 'login'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy', as:'logout'

  get '/index', to: "users#index", as: 'index'

  get '/profile/:id', to: "users#show", as: 'profile'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

private-club/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

private-club/app/models/user.rb
class User < ApplicationRecord

  validates :firstname, presence: true

  validates :lastname, presence: true

  validates :email, presence: true, uniqueness: true, format: /\w+@\w+\.{1}[a-zA-Z]{2,}/

end

private-club/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include SessionsHelper
  include UsersHelper
  before_action :require_login

  private

  def require_login
    unless user_signed_in?
      flash[:error] = "You must be logged in to access this section"
      redirect_to signup_url # halts request cycle
    end
  end

end

private-club/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  skip_before_action :require_login, only: [:new, :create]

  def new
  end

  def create
    @user = User.find_by(id: params[:session][:id])
    if @user
      log_in(@user)
      flash[:notice] = "Welcome! Access permitted!"
      redirect_to root_path
    else
      flash[:error] = "UNKNOW ID"
      render 'new'
    end
  end

  def destroy
    log_out
    redirect_to root_path
  end
end

private-club/app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController

  skip_before_action :require_login, only: :home

  def home
  end
end

private-club/app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_action :require_login, only: [:new, :create]

  def new
    @user = User.new
  end

  def create
    @user = User.create(params_user)
    if @user.save
      flash[:notice] = 'ACCOUNT WAS CREATED'
      log_in @user
      redirect_to root_path
    else
      flash[:error] = @user.errors.full_messages.join(" && ")
      redirect_to signup_url
    end
  end

  def edit
    @user = User.find(params[:id])
     if owner(@user)
     else
       flash[:error] = "YOU DON'T HAVE PERMISSION"
       redirect_to index_path
     end
  end

  def index
    @users = User.all
    @current_user = current_user
  end

  def update
    @user = User.find_by(id: params[:id])
    @user.update(params_user)
    if @user.save
      flash[:notice] = "CHANGING DONE"
      redirect_to index_path
    else
      flash[:error] = @user.errors.full_messages.join(" && ")
      redirect_to edit_user_path(@user.id)
    end
  end

  def show
    @user = User.find(params[:id])
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy
    redirect_to index_path
  end

  private

  def params_user
    params_user = params.require(:user).permit(:firstname, :lastname, :email)
  end

end

private-club/app/helpers/application_helper.rb
module ApplicationHelper
end

private-club/app/helpers/sessions_helper.rb
module SessionsHelper

    def log_in(user)
      session[:user_id] = user.id
    end

    def current_user
      @current_user ||= User.find_by(id: session[:user_id])
    end

    def user_signed_in?
    !current_user.nil?
    end

    def log_out
      session.delete(:user_id)
      @current_user = nil
    end

    def owner?
        if @user == current_user
        end
    end

  end

private-club/app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

private-club/app/helpers/users_helper.rb
module UsersHelper

  def owner(user)
    current_user
    if user == current_user
      return true
    else
      return false
    end
  end

end

private-club/app/views/layouts/_footer.html.erb
<div class="fixed-bottom">
  <ul class="nav d-flex justify-content-around">
      <li class="nav-item">
        <a class="btn btn-dark" href="#">Team BDX</a>
      </li>
      <li class="nav-item">
        <a class="btn btn-light" href="https://github.com/DaTikh" target="blank">@bab</a>
      </li>
      <li class="nav-item">
        <a class="btn btn-light" href="https://github.com/iMassim0" target="blank">@massimo</a>
      </li>
      <li class="nav-item">

        <a class="btn btn-warning" href="https://www.youtube.com/watch?v=uNagmAEtUCI" target="blank">M. LovaLova</a>
      </li>
  </ul>
</div>

private-club/app/views/layouts/_header.html.erb
<div class="fixed-top">
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="#">
    <img src="https://image.noelshack.com/fichiers/2018/19/1/1525702507-thp-bdx.png" width="40" height="40" class="d-inline-block align-top" alt=""></a>
  <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav" >
          <div class="p-2 bd-highlight">
            <li class="nav-item active">
              <%= link_to 'Home', root_path, class: "nav-link" %>
            </li>
          </div>
          <% if user_signed_in? %>
          <div class="p-2 bd-highlight">
            <li class="nav-item active">

            <a class="nav-link" href="<%= index_path %>">All clubbers</a>
            </li>
          </div>
        <% end %>
        </ul>
      <div class="ml-auto p-2 bd-highlight">
        <% if user_signed_in? %>
          <%= link_to "#{current_user.firstname}'s Page", profile_path(current_user), class: "btn btn-outline-success my-2 my-sm-0" %>
          <%= link_to 'Log out', logout_path, method: :delete, class: "btn btn-outline-danger my-2 my-sm-0"%>
        <% else %>
          <%= link_to 'Sign up', signup_path, class: "btn btn-outline-warning" %>
          <%= link_to 'Log in', login_path, class: "btn btn-outline-success" %>
        <% end %>
    </div>
  </div>
</nav>
</div>

private-club/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>🤫 Private Club</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.0/css/bootstrap.min.css" integrity="sha384-9gVQ4dYFwwWSjIDZnLEWnxCjeSWFphJiwGPXr1jddIhOegiu1FwO5qRGvFXOdJZ4" crossorigin="anonymous">
  </head>

  <body>
    <div class="blockquote text-center">
    <%= render 'layouts/header' %>

    <div id="container text-center">
      <% if flash[:notice] %>
        <p class="btn btn-outline-success"><%= flash[:notice] %></p>
      <% end %>
      <% if flash[:error] %>
        <p class="btn btn-outline-danger"><%= flash[:error] %></p>
      <% end %>

      <% flash[:error] = flash[:notice] = nil %>
    </div>

    <div class="start">
      <%= yield %>
    </div>
    <%= render 'layouts/footer' %>
    </div>
  </body>
</html>

private-club/app/views/static_pages/home.html.erb
<div class="container">
  <div>
    <% if user_signed_in? %>
      <h1>Welcome <%= @current_user.firstname %> <%= @current_user.lastname %>!</h1>
      <h2>Remember your Id : <%= @current_user.id %></h2>
      <%= link_to "Clubbeurs List", index_path, class: 'btn btn-outline-dark' %>
      <div class="bdx">
        <img src="https://image.noelshack.com/fichiers/2018/18/4/1525373439-thp-bdx.png" alt="logo thp bdx" class="logo"/>
      </div>
    <% else %>
        <h4 class="alert alert-danger ">Connexion requise pour aller sur ce site.</h4>
        <%= link_to "Sign up now", signup_path, class: "btn btn-primary", id: "signup_home" %>
        <%= link_to "Log in now", login_path, class: "btn btn-success", id: "login_home" %>
        <div class="bdx">
          <img src="https://image.noelshack.com/fichiers/2018/18/4/1525373439-thp-bdx.png" alt="logo thp bdx" class="logo"/>
        </div>
    <% end %>
  </div>

</div>

private-club/app/views/users/edit.html.erb
  <div class="container">
        <h1>Edit your account</h1>
        <div class="row">
          <div class="col-md-6 col-md-offset-3">
            <%= form_for(@user, url: {action: "update"}) do |f| %>
              <%= f.label :firstname %>
              <%= f.text_field :firstname, class: 'form-control' %>
              <br>
              <%= f.label :lastname %>
              <%= f.text_field :lastname, class: 'form-control' %>
              <br>
              <%= f.label :email %>
              <%= f.text_field :email, class: 'form-control' %>
              <br>
              <%= f.submit "Edit my account", class: "btn btn-primary" %>
            <% end %>
          </div>
        </div>
      </div>
    </div>

private-club/app/views/users/index.html.erb
<div class="container">
  <table class="table">
    <thead>
      <tr>
        <th scope="col">ID</th>
        <th scope="col">Firstname</th>
        <th scope="col">Lastname</th>
        <th scope="col">Email</th>
        <th scope="col">Valid?</th>
        <th scope="col">Link to profile</th>
        <th scope="col">Manage?</th>
        <th scope="col"></th>
      </tr>
    </thead>

    <tbody>
      <% @users.each do |user| %>
        <tr>
          <th scope="row"><%= user.id %></th>
          <td><%= user.firstname %></td>
          <td><%= user.lastname %></td>
          <td><%= user.email %></td>
          <td><%= user.valid? %></td>
          <td><%= link_to  "#{user.firstname}'s profile", profile_path(user), class: "btn btn-outline-dark" %></td>
          <% if owner(user) %>
            <td><%= link_to 'Update', edit_user_path(user), class: "btn btn-outline-warning"%></td>
            <td><%= link_to 'Delete', user, class: 'btn btn-outline-danger',
                                      method: :delete,
                 data: { confirm: 'Sur ?' } %></td>
          <% else %>
          <td><p class="badge badge-danger ">You don't have permission</p></td>
          <td></td>
        </tr>
        <% end %>
      <% end %>
    </tbody>
  </table>
</div>

private-club/app/views/users/new.html.erb
<div class="container">
        <h1>Sign up</h1>

        <div class="row">
          <div class="col-md-6 col-md-offset-3">
            <%= form_for(@user, url: {action: "create"}) do |f| %>
              <%= f.label :firstname %>
              <%= f.text_field :firstname, class: 'form-control', id: 'firstname'%>
<br>
              <%= f.label :lastname %>
              <%= f.text_field :lastname, class: 'form-control', id: 'lastname'%>
<br>
              <%= f.label :email %>
              <%= f.text_field :email, class: 'form-control', id: 'email'%>
<br>
              <%= f.submit "Create my account", class: "btn btn-primary" %>
            <% end %>
          </div>
        </div>
      </div>
    </div>

private-club/app/views/users/show.html.erb
<div class="container">
    <% if owner(@user) %>
    <h1>Your informations : <%= @current_user.firstname %> <%= @current_user.lastname %></h1>
    <h2>Your email : <%= @current_user.email %></h2>
    <br>
    <p class = "btn btn-warning"><%= link_to 'Update my informations', edit_user_path(current_user)%></p>
    <% else %>
    <h1>Profile of <%= @user.firstname %> <%= @user.lastname %></h1>
    <h2>Contact : <%= @user.email %></h2>
    <% end %>
</div>